### ISSUE TITLE
Add 2 new papers about topic modeling

### ISSUE THREAD

**Issue by personalization-trap** [BobXWu/Paper-Neural-Topic-Models#1]
Hi,

Thanks for your wonderful survey!

Would you mind adding 2 papers about topic modeling.

Paper 1: DeTiME: Diffusion-Enhanced Topic Modeling using Encoder-decoder based LLM
Accepted by EMNLP 2023 as findings.
It leverages diffusion for topic guided text generation. 
It is relevant to Applications of NTMs  / Text Generation
Paper link: https://aclanthology.org/2023.findings-emnlp.606.pdf

Paper 2: vONTSS: vMF based semi-supervised neural topic modeling with optimal transport
Accepted by ACL 2023 as findings.
It leverages vMF as prior for topic modeling.
It is relevant to NTM with Different Structure / NTMs with Various Priors
Paper link: https://aclanthology.org/2023.findings-acl.271/
Code link: https://github.com/xuweijieshuai/Neural-Topic-Modeling-vmf

Thanks a lot!

**Comment by bobxwu** [comment]
Hi, Thank you. You can create pull requests to add these papers.

**Comment by personalization-trap** [comment]
Sounds good. Thank you!
